name: Run OWASP dependency check and NodeJS vulnerability scanner

on:
    push:
        branches: [master]

jobs:
    sast:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [8.9.0]

        steps:
            - name: Check out source code
              uses: actions/checkout@v2

            # Run NodeJs Scanner
            - name: NodeJS Static Scan
              id: njsscan
              uses: ajinabraham/njsscan-action@master
              with:
                  args: ". --sarif --output results.sarif || true"

            # Upload NodeJS Scanner results to CodeQL and create security alerts
            - name: Upload NodeJS Static Scan report
              uses: github/codeql-action/upload-sarif@v1
              with:
                  sarif_file: results.sarif

            # Setup NodeJS to install modules for synk to look for
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            # Install the node modules and create package-lock.json file
            - name: Install the Node modules
              run: |
                  npm install
                  npm install --package-lock

            # Download and setup OWASP Dependency check report
            - name: Download and setup OWASP Dependency check
              run: |
                  download_link=`curl https://api.github.com/repos/jeremylong/DependencyCheck/releases/latest -s | grep browser_download_url | cut -d '"' -f4 | awk 'NR==1{print $1}'`
                  echo $download_link
                  wget $download_link -O /tmp/dependency-check.zip
                  cd /tmp/ && unzip dependency-check.zip

            # Run OWASP Dependency check
            - name: Run OWASP Dependency check
              run: |
                  echo $GITHUB_WORKSPACE
                  bash /tmp/dependency-check/bin/dependency-check.sh \
                  --scan $GITHUB_WORKSPACE \
                  --format "ALL" \
                  --project "dependency-check scan: $(pwd)" \
                  --out "$GITHUB_WORKSPACE/report"

            # Check vulns using synk
            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              continue-on-error: true
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

            # Some checks before the uploading of files
            - name: Check some stuff before uploading files
              run: |
                  echo ${{ github.workspace }}
                  echo $GITHUB_WORKSPACE
                  pwd
                  ls -lah
                  ls -lah report/
                  ls -lah results.arif
                  find report
                  find .

            # Upload artifacts of the tools run
            - name: Upload artifacts of SAST results
              uses: actions/upload-artifact@v2
              with:
                  name: sast-reports
                  path: |
                      "report"
                      "results.sarif"
