name: Run OWASP dependency check and NodeJS vulnerability scanner

on:
    push:
        branches: [master]

jobs:
    post:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [8.9.0]

        steps:
            - name: Check out source code
              uses: actions/checkout@v2

            # Download and setup OWASP Dependency check report
            - name: Download and setup OWASP Dependency check
              run: |
                  sudo apt-get update -y
                  sudo apt-get install -y wget curl zip unzip
                  download_link=`curl https://api.github.com/repos/jeremylong/DependencyCheck/releases/latest -s | grep browser_download_url | cut -d '"' -f4 | awk 'NR==1{print $1}'`
                  wget $download_link -O /tmp/dependency-check.zip
                  unzip /tmp/dependency-check.zip

            # Run OWASP Dependency check
            - name: Run OWASP Dependency check
              run: |
                  bash ./tmp/dependency-check/bin/dependency-check.sh \
                  --scan $GITHUB_WORKSPACE \
                  --format "ALL" \
                  --project "dependency-check scan: $(pwd)" \
                  --out /report

            # NodeJs Scanner
            - name: NodeJS Static Scan
              id: njsscan
              uses: ajinabraham/njsscan-action@master
              with:
                  args: ". --sarif --output results.sarif || true"

            - name: Upload NodeJS Static Scan report
              uses: github/codeql-action/upload-sarif@v1
              with:
                  sarif_file: results.sarif

            # Snyk scanning implementation (need to install node app and modoules first)
            - name: Install build-essentials to fix bcrypt error with node
              run: |
                  id

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install the Node modules
              run: |
                  npm install

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              continue-on-error: true
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
