name: Run OWASP dependency check and NodeJS vulnerability scanner

on:
    push:
        branches: [master]

jobs:
    post:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [8.9.0]

        steps:
            - name: Check out source code
              uses: actions/checkout@v2

            # NodeJs Scanner
            - name: NodeJS Static Scan
              id: njsscan
              uses: ajinabraham/njsscan-action@master
              with:
                  args: ". --sarif --output results.sarif || true"

            - name: Upload NodeJS Static Scan report
              uses: github/codeql-action/upload-sarif@v1
              with:
                  sarif_file: results.sarif

            # Snyk scanning implementation (need to install node app and modoules first)
            - name: Install build-essentials to fix bcrypt error with node
              run: |
                  id
                  sudo apt-get update -y
                  sudo apt-get install -y build-essential

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install the Node modules
              run: |
                  npm install

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              continue-on-error: true
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
